Migrate plugin and example to null safety
feilfeilundfeil/flutter_in_app_update pull request #62
Opened 2021-02-24 21:29 UTC by MooNag

This converts the master branch and example to null safety following the Android docs on AppUpdateInfo nullability.

I do not know how stable main is so there might need to be more changes before release to make this a stable migration. I tested the example app and got the expected error with a development build so everything seems to be working ok.

I also converted the deprecation to a full api change because this is a major version (has to be released as 2.0.0) might as well just make the breaking change.

`@Deprecated('Use updateAvailability instead.')
  final bool updateAvailable;`

2021-02-24 21:31 UTC, MooNag commented
fixes #62

2021-03-05 18:48 UTC, cedteg requested changes

2021-03-05 18:48 UTC, cedteg commented on example/pubspec.yaml
> +  sdk: ">=2.12.0-259.9.beta <3.0.0"
```suggestion
  sdk: ">=2.12.0 <3.0.0"
```

2021-03-05 18:48 UTC, cedteg commented on pubspec.yaml
> +  sdk: ">=2.12.0-259.9.beta <3.0.0"
```suggestion
  sdk: ">=2.12.0 <3.0.0"
```

2021-03-07 10:12 UTC, jonasbark commented
Thank you!

2021-03-07 10:12 UTC, merged